name: my-test workflow

on:
  push:
        branches:
        - master
  pull_request:
        branches:
        - master
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: hellow world
          run: echo "hello rabbits"
          shell: bash


